#ifndef ENUM_TIPO_OPERACAO_HPP
#define ENUM_TIPO_OPERACAO_HPP

using namespace frota;


namespace frota {
enum class EnumTipoOperacao{
    VISUALIZAR_VEICULOS,
    VISUALIZAR_MOTORISTAS,
    CADASTRAR_VEICULO,
    CADASTRAR_MOTORISTA,
    SELECIONAR_MOTORISTA,
    REMOVER_VEICULO,
    REMOVER_MOTORISTA,
    SAIR,
    INVALIDA
};
}

#endif